### ISSUE TITLE
Engine scans files in vendor/bundle

### ISSUE THREAD

**Issue by Bounga** [HipByte/codeclimate-rubymotion#4]
When I run `codeclimate analyse` with the rubymotion engine enabled it scan files in `vendor/bundle` and I'm pretty sure we don't want warning about code that doesn't belong to us ;-)

I don't know if there a way to override this in my local .codeclimate.yml file?

**Comment by gdiggs** [comment]
Hey @Bounga! You can [exclude that directory](https://docs.codeclimate.com/docs/excluding-files-and-folders) from analysis!
